version: "3.8"
services:
  app:
    container_name: video-editing
    image: video-editing
    build:
      context: ./fe-video-editing
      target: production
    ports:
      - "5002:80"
  api:
    container_name: video-editing-api
    build:
      context: ./be-video-editing
      dockerfile: video_editing_api\Dockerfile
    ports:
      - "8080:80"